import { body, type ValidationChain } from "express-validator"
import type { CollectionName } from "../models/defaultData"
import { APPOINTMENT_STATUSES, USER_ROLES } from "../types"

const requireNonEmptyObject = body().custom((value) => {
  if (typeof value !== "object" || value === null || Array.isArray(value) || Object.keys(value).length === 0) {
    throw new Error("Body request tidak boleh kosong")
  }
  return true
})

const optionalString = (field: string) => body(field).optional({ values: "falsy" }).isString().trim()
const requiredString = (field: string) => body(field).isString().trim().notEmpty()

export const collectionCreateSchemas: Partial<Record<CollectionName, ValidationChain[]>> = {
  users: [
    requiredString("username"),
    body("password").isString().isLength({ min: 6 }),
    requiredString("name"),
    body("email").isEmail(),
    body("role").isIn(USER_ROLES),
  ],
  patients: [
    requiredString("noRM"),
    requiredString("nik"),
    requiredString("name"),
    body("birthDate").isString().notEmpty(),
    body("gender").isIn(["Laki-laki", "Perempuan"]),
    requiredString("address"),
    requiredString("phone"),
    optionalString("email"),
    body("bloodType").optional({ values: "falsy" }).isIn(["A", "B", "AB", "O", ""]),
    optionalString("allergies"),
    optionalString("emergencyContact"),
    optionalString("emergencyPhone"),
  ],
  doctors: [
    requiredString("name"),
    requiredString("specialization"),
    requiredString("phone"),
    body("email").isEmail(),
    body("status").isIn(["Aktif", "Tidak Aktif"]),
    body("schedules").optional().isArray(),
  ],
  services: [
    requiredString("name"),
    body("category").isIn(["Konsultasi", "Pemeriksaan", "Tindakan", "Laboratorium", "Radiologi"]),
    body("price").isFloat({ min: 0 }),
    body("duration").isInt({ min: 0 }),
    optionalString("description"),
    body("status").isIn(["Aktif", "Tidak Aktif"]),
    body("applicableSpecializations").optional().isArray(),
  ],
  medicalCodes: [
    body("system").isIn(["icd10", "icd9cm"]),
    requiredString("code"),
    requiredString("name"),
    optionalString("category"),
    body("isActive").optional().isBoolean(),
  ],
  suppliers: [
    requiredString("code"),
    requiredString("name"),
    optionalString("contactPerson"),
    optionalString("phone"),
    optionalString("email"),
    optionalString("address"),
    body("status").optional().isIn(["aktif", "nonaktif"]),
    optionalString("notes"),
  ],
  purchaseOrders: [
    requiredString("poNumber"),
    requiredString("supplierId"),
    requiredString("supplierName"),
    body("status").optional().isIn(["draft", "dipesan", "diterima-sebagian", "selesai", "batal"]),
    body("orderDate").isString().notEmpty(),
    optionalString("expectedDate"),
    body("items").isArray({ min: 1 }),
    body("items.*.medicineId").isString().notEmpty(),
    body("items.*.quantity").isInt({ min: 1 }),
    body("items.*.unitPrice").isFloat({ min: 0 }),
    body("totalAmount").optional().isFloat({ min: 0 }),
    optionalString("notes"),
  ],
  expenses: [
    body("date").isString().notEmpty(),
    body("category").isIn(["gaji", "sewa", "utilitas", "pembelian-obat", "operasional", "pemeliharaan", "lainnya"]),
    requiredString("description"),
    body("amount").isFloat({ gt: 0 }),
    body("paymentMethod").isIn(["tunai", "transfer", "qris"]),
    optionalString("notes"),
    optionalString("recordedBy"),
  ],
  appointments: [
    requiredString("patientId"),
    requiredString("patientName"),
    requiredString("doctorId"),
    requiredString("doctorName"),
    optionalString("serviceId"),
    optionalString("serviceName"),
    body("serviceIds").optional().isArray(),
    body("serviceNames").optional().isArray(),
    body("date").isString().notEmpty(),
    body("time").isString().notEmpty(),
    body("status").optional().isIn(APPOINTMENT_STATUSES),
    body("queueNumber").optional().isInt({ min: 1 }),
    optionalString("notes"),
    body("triage").optional().isObject(),
  ],
  medicalRecords: [
    requiredString("patientId"),
    requiredString("appointmentId"),
    requiredString("doctorId"),
    requiredString("doctorName"),
    body("date").isString().notEmpty(),
    requiredString("diagnosis"),
    requiredString("symptoms"),
    requiredString("treatment"),
    body("soap").optional().isObject(),
    body("diagnosisCodes").optional().isArray(),
    body("procedureCodes").optional().isArray(),
    body("clinicalHistory").optional().isObject(),
    body("prescription").optional().isArray(),
    body("equipmentsUsed").optional().isArray(),
    body("vitalSigns").optional().isObject(),
    body("clinicalDecision").optional().isIn(["outpatient-discharge", "prescription", "lab-required", "radiology-required", "referral", "observation", "inpatient-required"]),
    optionalString("referralDestination"),
    optionalString("observationNotes"),
    body("status").optional().isIn(["draft", "completed", "locked"]),
    optionalString("notes"),
  ],
  labOrders: [
    requiredString("patientId"),
    requiredString("patientName"),
    requiredString("medicalRecordId"),
    optionalString("admissionId"),
    requiredString("doctorId"),
    requiredString("doctorName"),
    body("tests").isArray({ min: 1 }),
    body("priority").optional().isIn(["routine", "urgent"]),
    body("status").optional().isIn(["requested", "sample_taken", "processing", "completed", "reviewed", "cancelled"]),
    optionalString("notes"),
  ],
  labResults: [
    requiredString("patientId"),
    optionalString("labOrderId"),
    requiredString("testName"),
    requiredString("resultValue"),
    optionalString("unit"),
    optionalString("notes"),
    body("performedAt").isString().notEmpty(),
  ],
  radiologyOrders: [
    requiredString("patientId"),
    requiredString("patientName"),
    requiredString("medicalRecordId"),
    optionalString("admissionId"),
    requiredString("doctorId"),
    requiredString("doctorName"),
    requiredString("study"),
    body("priority").optional().isIn(["routine", "urgent"]),
    body("status").optional().isIn(["requested", "scheduled", "performed", "reported", "reviewed", "cancelled"]),
    optionalString("indication"),
    optionalString("findings"),
    optionalString("impression"),
  ],
  clinicalDocuments: [
    requiredString("patientId"),
    requiredString("patientName"),
    optionalString("medicalRecordId"),
    body("type").isIn(["medical-resume", "referral-letter", "informed-consent", "control-letter", "sick-letter"]),
    requiredString("title"),
    requiredString("content"),
    body("status").optional().isIn(["draft", "final"]),
    optionalString("signedBy"),
    optionalString("signedAt"),
  ],
  informedConsents: [
    requiredString("patientId"),
    requiredString("patientName"),
    optionalString("medicalRecordId"),
    optionalString("admissionId"),
    body("consentType").isIn([
      "tindakan-medis",
      "tindakan-bedah",
      "anestesi",
      "rawat-inap",
      "transfusi-darah",
      "persetujuan-umum",
    ]),
    requiredString("procedureName"),
    optionalString("procedureCode"),
    optionalString("doctorId"),
    optionalString("doctorName"),
    optionalString("diagnosis"),
    optionalString("indication"),
    optionalString("risks"),
    optionalString("alternatives"),
    optionalString("prognosis"),
    body("grantedBy").isIn(["pasien", "wali"]),
    optionalString("guardianName"),
    optionalString("guardianRelation"),
    optionalString("guardianNik"),
    optionalString("witnessName"),
    body("decision").isIn(["setuju", "menolak"]),
    body("status").optional().isIn(["draft", "signed"]),
    optionalString("signedAt"),
    optionalString("signedLocation"),
    optionalString("notes"),
  ],
  referralFacilities: [
    requiredString("name"),
    body("type").optional().isIn(["rumah-sakit", "klinik", "puskesmas", "lainnya"]),
    optionalString("address"),
    optionalString("phone"),
    optionalString("notes"),
  ],
  medicines: [
    requiredString("code"),
    requiredString("name"),
    requiredString("genericName"),
    optionalString("brandName"),
    body("category").isIn(["Obat Bebas", "Obat Bebas Terbatas", "Obat Keras", "Obat Narkotika"]),
    body("form").optional().isIn(["Tablet", "Kapsul", "Sirup", "Injeksi", "Salep", "Tetes", "Inhaler"]),
    optionalString("strength"),
    requiredString("unit"),
    body("stock").isNumeric(),
    body("minStock").optional().isNumeric(),
    body("maxStock").optional().isNumeric(),
    body("price").isNumeric(),
    body("buyPrice").optional().isNumeric(),
    body("sellPrice").optional().isNumeric(),
    requiredString("manufacturer"),
    optionalString("supplier"),
    optionalString("batchNumber"),
    body("expiryDate").isString().notEmpty(),
    optionalString("location"),
    optionalString("barcode"),
    optionalString("description"),
    body("status").optional().isIn(["Tersedia", "Stok Rendah", "Habis"]),
    body("isActive").optional().isBoolean(),
    body("requiresPrescription").optional().isBoolean(),
  ],
  medicalEquipments: [
    requiredString("code"),
    requiredString("name"),
    body("category").isIn(["Diagnostik", "Terapeutik", "Bedah", "Sterilisasi", "Monitoring", "Lainnya"]),
    requiredString("brand"),
    requiredString("model"),
    body("quantity").isInt({ min: 0 }),
    body("condition").isIn(["Baik", "Perlu Perbaikan", "Rusak"]),
    requiredString("location"),
    body("purchaseDate").isString().notEmpty(),
    optionalString("lastMaintenanceDate"),
    optionalString("nextMaintenanceDate"),
    optionalString("notes"),
    body("status").isIn(["Tersedia", "Digunakan", "Dalam Perawatan", "Tidak Aktif"]),
  ],
  payments: [
    requiredString("medicalRecordId"),
    requiredString("patientId"),
    body("amount").isFloat({ gt: 0 }),
    body("method").isIn(["tunai", "transfer-himbara", "qris", "asuransi-swasta", "asuransi-bumn", "asuransi-syariah", "bpjs"]),
    body("paymentSource").optional().isIn(["patient", "insurance"]),
    optionalString("insuranceClaimId"),
    optionalString("notes"),
    body("paidAt").optional().isString(),
  ],
  billingRecords: [
    requiredString("medicalRecordId"),
    requiredString("patientId"),
    body("total").isNumeric(),
    body("status").optional().isIn(["draft", "calculated", "waiting_payment", "partially_paid", "paid", "claimed_to_insurance", "cancelled"]),
  ],
  pharmacyRequests: [
    requiredString("medicalRecordId"),
    requiredString("patientId"),
    requiredString("patientName"),
    body("items").optional().isArray(),
    body("prescription").optional().isArray(),
    body("status").optional().isIn(["requested", "processing", "fulfilled", "cancelled", "pending", "verified", "dispensed"]),
    optionalString("verificationNotes"),
    optionalString("dispensingNotes"),
    optionalString("notes"),
  ],
  insuranceProfiles: [
    requiredString("patientId"),
    requiredString("patientName"),
    body("provider").isIn(["bpjs", "asuransi-swasta"]),
    requiredString("policyNumber"),
    requiredString("planName"),
    body("validUntil").isString().notEmpty(),
    body("rateMultiplier").isFloat({ min: 0 }),
    optionalString("coverageNotes"),
    optionalString("lastVerifiedAt"),
  ],
  insuranceBridgeMembers: [
    requiredString("participantNumber"),
    requiredString("name"),
    requiredString("facility"),
    body("status").isIn(["aktif", "non-aktif"]),
    body("coverageLevel").isIn(["primer", "sekunder"]),
    body("lastClaimDate").isString().notEmpty(),
  ],
  beds: [
    requiredString("bedNumber"),
    requiredString("ward"),
    body("status").optional().isIn(["available", "occupied", "cleaning", "maintenance"]),
    optionalString("lastCleanedAt"),
    optionalString("assignedPatientId"),
  ],
  inpatientAdmissions: [
    requiredString("patientId"),
    requiredString("patientName"),
    requiredString("bedId"),
    requiredString("bedNumber"),
    requiredString("ward"),
    body("admittedAt").isString().notEmpty(),
    body("expectedDischarge").optional({ values: "falsy" }).isString(),
    body("status").optional().isIn(["ongoing", "discharged", "pending", "referred", "deceased"]),
    optionalString("attendingDoctorId"),
    optionalString("attendingDoctorName"),
    optionalString("notes"),
    optionalString("medicalRecordId"),
  ],
  doctorVisitNotes: [
    requiredString("admissionId"),
    requiredString("doctorId"),
    requiredString("doctorName"),
    body("date").isString().notEmpty(),
    requiredString("note"),
  ],
  patientNotifications: [
    requiredString("patientId"),
    requiredString("patientName"),
    body("channel").isIn(["sms", "whatsapp", "email"]),
    requiredString("message"),
    body("targetAt").isString().notEmpty(),
    body("status").optional().isIn(["pending", "processing", "sent", "failed"]),
  ],
  satisfactionSurveys: [
    requiredString("patientId"),
    requiredString("patientName"),
    body("rating").isInt({ min: 1, max: 5 }),
    optionalString("comments"),
    body("submittedAt").optional().isString(),
  ],
  clinicSettings: [
    requiredString("name"),
    requiredString("address"),
    requiredString("phone"),
    body("email").isEmail(),
    requiredString("operationalHours"),
    optionalString("description"),
  ],
}

export const collectionUpdateSchemas: Partial<Record<CollectionName, ValidationChain[]>> = {
  users: [
    requireNonEmptyObject,
    body("username").optional().isString().trim().notEmpty(),
    body("password").optional().isString().isLength({ min: 6 }),
    body("name").optional().isString().trim().notEmpty(),
    body("email").optional().isEmail(),
    body("role").optional().isIn(USER_ROLES),
  ],
  patients: [
    requireNonEmptyObject,
    optionalString("noRM"),
    optionalString("nik"),
    optionalString("name"),
    body("birthDate").optional().isString(),
    body("gender").optional().isIn(["Laki-laki", "Perempuan"]),
    optionalString("address"),
    optionalString("phone"),
    optionalString("email"),
    body("bloodType").optional({ values: "falsy" }).isIn(["A", "B", "AB", "O", ""]),
    optionalString("allergies"),
    optionalString("emergencyContact"),
    optionalString("emergencyPhone"),
  ],
  doctors: [
    requireNonEmptyObject,
    optionalString("name"),
    optionalString("specialization"),
    optionalString("phone"),
    body("email").optional().isEmail(),
    body("status").optional().isIn(["Aktif", "Tidak Aktif"]),
    body("schedules").optional().isArray(),
  ],
  services: [
    requireNonEmptyObject,
    optionalString("name"),
    body("category").optional().isIn(["Konsultasi", "Pemeriksaan", "Tindakan", "Laboratorium", "Radiologi"]),
    body("price").optional().isFloat({ min: 0 }),
    body("duration").optional().isInt({ min: 0 }),
    optionalString("description"),
    body("status").optional().isIn(["Aktif", "Tidak Aktif"]),
    body("applicableSpecializations").optional().isArray(),
  ],
  medicalCodes: [
    requireNonEmptyObject,
    body("system").optional().isIn(["icd10", "icd9cm"]),
    optionalString("code"),
    optionalString("name"),
    optionalString("category"),
    body("isActive").optional().isBoolean(),
  ],
  suppliers: [
    requireNonEmptyObject,
    optionalString("code"),
    optionalString("name"),
    optionalString("contactPerson"),
    optionalString("phone"),
    optionalString("email"),
    optionalString("address"),
    body("status").optional().isIn(["aktif", "nonaktif"]),
    optionalString("notes"),
  ],
  purchaseOrders: [
    requireNonEmptyObject,
    optionalString("poNumber"),
    optionalString("supplierId"),
    optionalString("supplierName"),
    body("status").optional().isIn(["draft", "dipesan", "diterima-sebagian", "selesai", "batal"]),
    optionalString("orderDate"),
    optionalString("expectedDate"),
    body("items").optional().isArray(),
    body("totalAmount").optional().isFloat({ min: 0 }),
    optionalString("notes"),
  ],
  expenses: [
    requireNonEmptyObject,
    optionalString("date"),
    body("category").optional().isIn(["gaji", "sewa", "utilitas", "pembelian-obat", "operasional", "pemeliharaan", "lainnya"]),
    optionalString("description"),
    body("amount").optional().isFloat({ gt: 0 }),
    body("paymentMethod").optional().isIn(["tunai", "transfer", "qris"]),
    optionalString("notes"),
  ],
  appointments: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("patientName"),
    optionalString("doctorId"),
    optionalString("doctorName"),
    optionalString("serviceId"),
    optionalString("serviceName"),
    body("serviceIds").optional().isArray(),
    body("serviceNames").optional().isArray(),
    body("date").optional().isString(),
    body("time").optional().isString(),
    body("status").optional().isIn(APPOINTMENT_STATUSES),
    body("queueNumber").optional().isInt({ min: 1 }),
    optionalString("notes"),
    body("triage").optional().isObject(),
  ],
  medicalRecords: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("appointmentId"),
    optionalString("doctorId"),
    optionalString("doctorName"),
    body("date").optional().isString(),
    optionalString("diagnosis"),
    optionalString("symptoms"),
    optionalString("treatment"),
    body("soap").optional().isObject(),
    body("diagnosisCodes").optional().isArray(),
    body("procedureCodes").optional().isArray(),
    body("clinicalHistory").optional().isObject(),
    body("prescription").optional().isArray(),
    body("equipmentsUsed").optional().isArray(),
    body("vitalSigns").optional().isObject(),
    body("clinicalDecision").optional().isIn(["outpatient-discharge", "prescription", "lab-required", "radiology-required", "referral", "observation", "inpatient-required"]),
    optionalString("referralDestination"),
    optionalString("observationNotes"),
    body("status").optional().isIn(["draft", "completed", "locked"]),
    optionalString("notes"),
    optionalString("auditReason"),
  ],
  medicines: [
    requireNonEmptyObject,
    optionalString("code"),
    optionalString("name"),
    optionalString("genericName"),
    optionalString("brandName"),
    body("category").optional().isIn(["Obat Bebas", "Obat Bebas Terbatas", "Obat Keras", "Obat Narkotika"]),
    body("form").optional().isIn(["Tablet", "Kapsul", "Sirup", "Injeksi", "Salep", "Tetes", "Inhaler"]),
    optionalString("strength"),
    optionalString("unit"),
    body("stock").optional().isNumeric(),
    body("minStock").optional().isNumeric(),
    body("maxStock").optional().isNumeric(),
    body("price").optional().isNumeric(),
    body("buyPrice").optional().isNumeric(),
    body("sellPrice").optional().isNumeric(),
    optionalString("manufacturer"),
    optionalString("supplier"),
    optionalString("batchNumber"),
    body("expiryDate").optional().isString(),
    optionalString("location"),
    optionalString("barcode"),
    optionalString("description"),
    body("status").optional().isIn(["Tersedia", "Stok Rendah", "Habis"]),
    body("isActive").optional().isBoolean(),
    body("requiresPrescription").optional().isBoolean(),
  ],
  medicalEquipments: [
    requireNonEmptyObject,
    optionalString("code"),
    optionalString("name"),
    body("category").optional().isIn(["Diagnostik", "Terapeutik", "Bedah", "Sterilisasi", "Monitoring", "Lainnya"]),
    optionalString("brand"),
    optionalString("model"),
    body("quantity").optional().isInt({ min: 0 }),
    body("condition").optional().isIn(["Baik", "Perlu Perbaikan", "Rusak"]),
    optionalString("location"),
    body("purchaseDate").optional().isString(),
    optionalString("lastMaintenanceDate"),
    optionalString("nextMaintenanceDate"),
    optionalString("notes"),
    body("status").optional().isIn(["Tersedia", "Digunakan", "Dalam Perawatan", "Tidak Aktif"]),
  ],
  labOrders: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("patientName"),
    optionalString("medicalRecordId"),
    optionalString("admissionId"),
    optionalString("doctorId"),
    optionalString("doctorName"),
    body("tests").optional().isArray(),
    body("priority").optional().isIn(["routine", "urgent"]),
    body("status").optional().isIn(["requested", "sample_taken", "processing", "completed", "reviewed", "cancelled"]),
    optionalString("notes"),
  ],
  labResults: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("labOrderId"),
    optionalString("testName"),
    optionalString("resultValue"),
    optionalString("unit"),
    optionalString("notes"),
    body("performedAt").optional().isString(),
  ],
  radiologyOrders: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("patientName"),
    optionalString("medicalRecordId"),
    optionalString("admissionId"),
    optionalString("doctorId"),
    optionalString("doctorName"),
    optionalString("study"),
    body("priority").optional().isIn(["routine", "urgent"]),
    body("status").optional().isIn(["requested", "scheduled", "performed", "reported", "reviewed", "cancelled"]),
    optionalString("indication"),
    optionalString("findings"),
    optionalString("impression"),
    optionalString("reviewedAt"),
    optionalString("reviewedByDoctorId"),
    optionalString("reviewedByDoctorName"),
  ],
  referralFacilities: [
    requireNonEmptyObject,
    optionalString("name"),
    body("type").optional().isIn(["rumah-sakit", "klinik", "puskesmas", "lainnya"]),
    optionalString("address"),
    optionalString("phone"),
    optionalString("notes"),
  ],
  clinicalDocuments: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("patientName"),
    optionalString("medicalRecordId"),
    body("type").optional().isIn(["medical-resume", "referral-letter", "informed-consent", "control-letter", "sick-letter"]),
    optionalString("title"),
    optionalString("content"),
    body("status").optional().isIn(["draft", "final"]),
    optionalString("signedBy"),
    optionalString("signedAt"),
  ],
  informedConsents: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("patientName"),
    optionalString("medicalRecordId"),
    optionalString("admissionId"),
    body("consentType").optional().isIn([
      "tindakan-medis",
      "tindakan-bedah",
      "anestesi",
      "rawat-inap",
      "transfusi-darah",
      "persetujuan-umum",
    ]),
    optionalString("procedureName"),
    optionalString("procedureCode"),
    optionalString("doctorId"),
    optionalString("doctorName"),
    optionalString("diagnosis"),
    optionalString("indication"),
    optionalString("risks"),
    optionalString("alternatives"),
    optionalString("prognosis"),
    body("grantedBy").optional().isIn(["pasien", "wali"]),
    optionalString("guardianName"),
    optionalString("guardianRelation"),
    optionalString("guardianNik"),
    optionalString("witnessName"),
    body("decision").optional().isIn(["setuju", "menolak"]),
    body("status").optional().isIn(["draft", "signed"]),
    optionalString("signedAt"),
    optionalString("signedLocation"),
    optionalString("notes"),
  ],
  payments: [
    requireNonEmptyObject,
    optionalString("medicalRecordId"),
    optionalString("patientId"),
    body("amount").optional().isFloat({ gt: 0 }),
    body("method").optional().isIn(["tunai", "transfer-himbara", "qris", "asuransi-swasta", "asuransi-bumn", "asuransi-syariah", "bpjs"]),
    body("paymentSource").optional().isIn(["patient", "insurance"]),
    optionalString("insuranceClaimId"),
    optionalString("notes"),
    body("paidAt").optional().isString(),
  ],
  billingRecords: [
    requireNonEmptyObject,
    optionalString("medicalRecordId"),
    optionalString("patientId"),
    body("total").optional().isNumeric(),
    body("status").optional().isIn(["draft", "calculated", "waiting_payment", "partially_paid", "paid", "claimed_to_insurance", "cancelled"]),
    optionalString("notes"),
  ],
  pharmacyRequests: [
    requireNonEmptyObject,
    optionalString("medicalRecordId"),
    optionalString("patientId"),
    optionalString("patientName"),
    body("items").optional().isArray(),
    body("prescription").optional().isArray(),
    body("status").optional().isIn(["requested", "processing", "fulfilled", "cancelled", "pending", "verified", "dispensed"]),
    optionalString("verificationNotes"),
    optionalString("dispensingNotes"),
    optionalString("notes"),
  ],
  insuranceProfiles: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("patientName"),
    body("provider").optional().isIn(["bpjs", "asuransi-swasta"]),
    optionalString("policyNumber"),
    optionalString("planName"),
    body("validUntil").optional().isString(),
    body("rateMultiplier").optional().isFloat({ min: 0 }),
    optionalString("coverageNotes"),
    optionalString("lastVerifiedAt"),
  ],
  insuranceBridgeMembers: [
    requireNonEmptyObject,
    optionalString("participantNumber"),
    optionalString("name"),
    optionalString("facility"),
    body("status").optional().isIn(["aktif", "non-aktif"]),
    body("coverageLevel").optional().isIn(["primer", "sekunder"]),
    body("lastClaimDate").optional().isString(),
  ],
  beds: [
    requireNonEmptyObject,
    optionalString("bedNumber"),
    optionalString("ward"),
    body("status").optional().isIn(["available", "occupied", "cleaning", "maintenance"]),
    optionalString("lastCleanedAt"),
    optionalString("assignedPatientId"),
  ],
  inpatientAdmissions: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("patientName"),
    optionalString("bedId"),
    optionalString("bedNumber"),
    optionalString("ward"),
    body("admittedAt").optional().isString(),
    body("expectedDischarge").optional({ values: "falsy" }).isString(),
    body("status").optional().isIn(["ongoing", "discharged", "pending", "referred", "deceased"]),
    optionalString("attendingDoctorId"),
    optionalString("attendingDoctorName"),
    optionalString("notes"),
    optionalString("medicalRecordId"),
  ],
  doctorVisitNotes: [
    requireNonEmptyObject,
    optionalString("admissionId"),
    optionalString("doctorId"),
    optionalString("doctorName"),
    body("date").optional().isString(),
    optionalString("note"),
  ],
  patientNotifications: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("patientName"),
    body("channel").optional().isIn(["sms", "whatsapp", "email"]),
    optionalString("message"),
    body("targetAt").optional().isString(),
    body("status").optional().isIn(["pending", "processing", "sent", "failed"]),
  ],
  satisfactionSurveys: [
    requireNonEmptyObject,
    optionalString("patientId"),
    optionalString("patientName"),
    body("rating").optional().isInt({ min: 1, max: 5 }),
    optionalString("comments"),
    body("submittedAt").optional().isString(),
  ],
  clinicSettings: [
    requireNonEmptyObject,
    optionalString("name"),
    optionalString("address"),
    optionalString("phone"),
    body("email").optional().isEmail(),
    optionalString("operationalHours"),
    optionalString("description"),
  ],
}
