services:
  mysql:
    ports:
      - "127.0.0.1:${MYSQL_HOST_PORT:-3307}:3306"

  backend:
    build:
      target: build
    command: npm run dev:backend
    environment:
      NODE_ENV: development
    ports:
      - "127.0.0.1:${API_PORT:-4004}:4004"
    volumes:
      - ../apps/backend/src:/app/apps/backend/src

  frontend:
    build:
      target: dependencies
    command: npm run dev:frontend -- --hostname 0.0.0.0
    environment:
      NODE_ENV: development
    volumes:
      - ../apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
      - /app/apps/frontend/.next
